### ISSUE TITLE
[CI] build image parameter and metric parameters

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#1276]
we have lots of duplicate code blocks in CI for image build.
- base image
- image with tag as dgcm
- validation image
- image for PR build as localhost... during integration test

if ... we can make 
```
    strategy:
      fail-fast: false
      matrix:
        include:
           image_file:
           arch:
           tag:
           build_arg:
           push:
           artifactory:
...
```
so that we can save time and effort to maintain docker build tags at different place.
