### ISSUE TITLE
Add a pre-commit checks and CI pipeline for python code

### ISSUE THREAD

**Issue by dave-tucker** [sustainable-computing-io/kepler#1544]
### What would you like to be added?

A CI pipeline and pre-commit checks that:

- checks formatting
- runs tests

for the e2e/validator code

### Why is this needed?

Because as it stands running `hatch fmt` against the code shows a lot of issues.
It will make formatting consistent and the code much easier to review if we have some pre-commit testing and CI.

**Comment by dave-tucker** [comment]
Example pre-commit config:
```
repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: hatch fmt
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
```
