### ISSUE TITLE
github-action user can't push commit back

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler#206]
**Describe the bug**
github-action user can't push commit back

**To Reproduce**
1. See error https://github.com/sustainable-computing-io/kepler/actions/runs/3079415202/jobs/4980117646#step:9:7

**Expected behavior**
github-action can push commit back as sample https://github.com/SamYuan1990/kepler/commit/62d342d974d9681ff94e4537e851174f3fce7b4d

**Screenshots**
n/A

**Desktop (please complete the following information):**
n/A

**Smartphone (please complete the following information):**
n/A

**Additional context**
n/A

**Comment by SamYuan1990** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/7820992/190996091-28862326-e989-4fc8-ae71-f1eed91f0b4d.png">
local fork setting is empty

**Comment by rootfs** [comment]
finally, we had our [first bot commit](https://github.com/sustainable-computing-io/kepler/commit/4af2a4a3357833f047aac637dfcd9c1f9ce05e5d)

**Comment by rootfs** [comment]
This is what I've done:
- create a bot account, create a personal access token (PAT)
- add the bot account into repo with write permission
- add bot PAT to GH secrets
- allow bot to bypass:
![image](https://user-images.githubusercontent.com/7062400/191328720-d0b4e5ca-70e6-4aec-b661-6afbfa60c3cb.png)
- add the following to GH top action:
```yaml
permissions:
  pull-requests: write
  contents: write
  repository-projects: write
```
- add the following to GH checkout action (this is very important!!!)
```yaml
- uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
```
- use the bot to push changes:
```yaml
    - name: Commit changes
      if: github.event_name != 'pull_request' && steps.verify-changed-files.outputs.files_changed == 'true' 
      run: |
        git config --local user.email "info@sustainable-computing.io"
        git config --local user.name "sustainabile-computing-bot"
        git add README.md
        git commit -m "bot: Updated coverage badge."
    - name: Push changes
      if: github.event_name != 'pull_request' && steps.verify-changed-files.outputs.files_changed == 'true' 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_BOT_SECRET }}
        branch: ${{ github.head_ref }}
```
