### ISSUE TITLE
keplerExporter-serviceMonitor.yaml contains clusterrole?

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#224]
**Describe the bug**

keplerExporter-serviceMonitor.yaml has a clusterrole
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes/metrics
  - verbs:
      - get
    nonResourceURLs:
      - /metrics

```
but kube-prometheus/manifests/prometheus-clusterRole.yaml has such
so we will be reported such clusterrole exist 

should we either remove this role defintion in our repo / sync the contents? 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.38.0
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get

```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
