### ISSUE TITLE
Enable deploying Kepler DS to master/admin nodes with taint.

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#526]
**Is your feature request related to a problem? Please describe.**

According to the issue raised by @SamYuan1990 in project channel, in general, kube master/admin nodes is usually initialized with taint to avoid user workload to be scheduled. Currently, kepler DS does not have toleration to any taint. So, it cannot monitor metrics in the master/admin nodes. 

**Describe the solution you'd like**

We might consider adding common toleration to Kepler DS such as the `node-role.kubernetes.io/master` taint. 

```yaml
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
```

Should this be default (and removable) in helm value or operator's kepler CR?

**Describe alternatives you've considered**

**Additional context**

Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>
