### ISSUE TITLE
Conflict between Kepler-exporter and OVN Kubernetes (regression?)

### ISSUE THREAD

**Issue by chr15p** [sustainable-computing-io/kepler#527]
**Describe the bug**
When installing Kepler on a single node openshift machine (i.e. with control plane on the same node as the worker)  the kepler-exporter pod gets stuck in Pending due to OVN Kubernetes already using port 9102. This appears to be exactly the same as #71   and I suspect the regression was caused by #449  

```
NAME                        READY   STATUS    RESTARTS   AGE                                                                                                  
pod/kepler-exporter-d6p4z   0/1     Pending   0          24s  
```
oc describe shows the following event:
```
 Warning  FailedScheduling  4s (x2 over 42s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod. 
```

(single node openshift is running the control-plane, master, and worker nodes on the same physical machine so they are sharing a set of hostPorts)

I got the pod to start by editing the built _output/generated-manifest/deployment.yaml file and removing:
```
+++ _output/generated-manifest/deployment.yaml  2023-02-08 12:40:13.619617925 +0000
@@ -135,7 +135,6 @@
         name: kepler-exporter
         ports:
         - containerPort: 9102
-          hostPort: 9102
           name: http
         resources:
           requests:
@@ -158,7 +157,6 @@
           name: cfm
           readOnly: true
       dnsPolicy: ClusterFirstWithHostNet
-      hostNetwork: true
       serviceAccountName: kepler-sa
       tolerations:
       - effect: NoSchedule
```
I haven't tested if this has broken anything else yet.

**To Reproduce**
1 . Install openshift
2. follow https://github.com/sustainable-computing-io/kepler/tree/main/manifests#installing-kepler-on-openshift
3. make build-manifest OPTS="OPENSHIFT_DEPLOY CLUSTER_PREREQ_DEPLOY"
4. kubectl create -f _output/generated-manifest/deployment.yaml

**versions**
Openshift 4.12
```
# oc version
Client Version: 4.9.17
Server Version: 4.12.0
Kubernetes Version: v1.25.4+77bec7a
```

**Expected behavior**
The pod should deploy
