### ISSUE TITLE
 LR Model (DynComponentModelWeight):

### ISSUE THREAD

**Issue by loko97170** [sustainable-computing-io/kepler#743]
**Is your feature request related to a problem? Please describe.**
Debug with Huamin  because the metrics are nulls and the kepler model server is not applicated.
We are on airgapped environment and we need to have model kepler on an image because we've this error:

 model.go:87] Model Config CONTAINER_COMPONENTS: {UseEstimatorSidecar:false SelectedModel: SelectFilter: InitModelURL:https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json}
I0620 13:32:38.242168       1 lr.go:164] LR Model (DynComponentModelWeight): loadWeightFromURLorLocal(https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json): <nil>
lr.go:173] LR Model (DynComponentModelWeight): connection error: Get "https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json": dial tcp: lookup raw.githubusercontent.com on 172.30.0.10:53: no such host (https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json)

**Describe the solution you'd like**
I want to have metrics not null .

**Comment by rootfs** [comment]
@jichenjc can you check if the prepackaged models are missing?

**Comment by marceloamaral** [comment]
@sunya-ch ^^

**Comment by jichenjc** [comment]
um.. is the latest image used? 

https://github.com/sustainable-computing-io/kepler/blob/main/build/Dockerfile#L31
is the DOcker file that we copy those files directly when bulid the image and it will avoid 
reach the github when it's a airgaped env .. 

https://github.com/sustainable-computing-io/kepler/blob/main/pkg/model/container_power.go#L39
is the code that consume the model

**Comment by rootfs** [comment]
I see, the default configmap (below) still uses remote `CONTAINER_COMPONENTS_INIT_URL`, it needs to be removed in order to use the local model.

```yaml
apiVersion: v1
data:
  BIND_ADDRESS: 0.0.0.0:9102
  CGROUP_METRICS: '*'
  CPU_ARCH_OVERRIDE: ""
  ENABLE_EBPF_CGROUPID: "true"
  ENABLE_GPU: "true"
  ENABLE_PROCESS_METRICS: "false"
  EXPOSE_CGROUP_METRICS: "true"
  EXPOSE_HW_COUNTER_METRICS: "true"
  EXPOSE_IRQ_COUNTER_METRICS: "true"
  EXPOSE_KUBELET_METRICS: "true"
  KEPLER_LOG_LEVEL: "1"
  KEPLER_NAMESPACE: kepler
  METRIC_PATH: /metrics
  MODEL_CONFIG: |
    CONTAINER_COMPONENTS_ESTIMATOR=false
   CONTAINER_COMPONENTS_INIT_URL=https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-server/main/tests/test_models/DynComponentModelWeight/CgroupOnly/ScikitMixed/ScikitMixed.json
kind: ConfigMap
metadata:
  labels:
    sustainable-computing.io/app: kepler
  name: kepler-cfm
  namespace: kepler
```

@loko97170 can you update the configmap to the following (i.e. remove `CONTAINER_COMPONENTS_INIT_URL`)?
```yaml
apiVersion: v1
data:
  BIND_ADDRESS: 0.0.0.0:9102
  CGROUP_METRICS: '*'
  CPU_ARCH_OVERRIDE: ""
  ENABLE_EBPF_CGROUPID: "true"
  ENABLE_GPU: "true"
  ENABLE_PROCESS_METRICS: "false"
  EXPOSE_CGROUP_METRICS: "true"
  EXPOSE_HW_COUNTER_METRICS: "true"
  EXPOSE_IRQ_COUNTER_METRICS: "true"
  EXPOSE_KUBELET_METRICS: "true"
  KEPLER_LOG_LEVEL: "1"
  KEPLER_NAMESPACE: kepler
  METRIC_PATH: /metrics
  MODEL_CONFIG: |
    CONTAINER_COMPONENTS_ESTIMATOR=false
kind: ConfigMap
metadata:
  labels:
    sustainable-computing.io/app: kepler
  name: kepler-cfm
  namespace: kepler
```

**Comment by jichenjc** [comment]
um.. `CONTAINER_COMPONENTS_INIT_URL` seems not used in current code. and not in kepler-model-server as well now

**Comment by sunya-ch** [comment]
It seems like the pod has no internet connection. To use the local, you may need to remove the value of initmodel in the configmap. 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler-cfm
data:
  KEPLER_NAMESPACE: $(KEPLER_NAMESPACE)
  KEPLER_LOG_LEVEL: "1"
  METRIC_PATH: "/metrics"
  BIND_ADDRESS: "0.0.0.0:9102"
  ENABLE_GPU: "true"
  ENABLE_EBPF_CGROUPID: "true"
  EXPOSE_HW_COUNTER_METRICS: "true"
  EXPOSE_IRQ_COUNTER_METRICS: "true"
  EXPOSE_KUBELET_METRICS: "true"
  EXPOSE_CGROUP_METRICS: "true"
  ENABLE_PROCESS_METRICS: "false"
  CPU_ARCH_OVERRIDE: ""
  CGROUP_METRICS: '*'
  MODEL_CONFIG: |
    CONTAINER_COMPONENTS_ESTIMATOR=false
    CONTAINER_COMPONENTS_INIT_URL=http:....  <-- remove this key
```


FYI, related source code logic

https://github.com/sustainable-computing-io/kepler/blob/f0e64598286350b7215bcb26679fd0c0864fbdd9/pkg/model/container_power.go#L43-L49
